//COMMON

// AUTH
export const AUTH_CHANGE_STATE = 'AUTH_CHANGE_STATE';
export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_RESPONSE = 'SIGNUP_RESPONSE';
export const OTP_VERIFICATION_REQUEST = 'OTP_VERIFICATION_REQUEST';
export const OTP_VERIFICATION_RESPONSE = 'OTP_VERIFICATION_RESPONSE';